<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>jade</string>
	</array>
	<key>name</key>
	<string>Jade</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.control.import.include.jade</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.control.import.include.jade</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(include|yield|append|prepend|block( (append|prepend))?)\s+(.*)</string>
			<key>name</key>
			<string>meta.first-class.jade</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^(!!!)(\s*[a-zA-Z0-9-_]+)?</string>
			<key>name</key>
			<string>comment.other.doctype.jade</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)//-</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>comment.unbuffered.block.jade</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)//</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>string.comment.buffered.block.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>invalid.illegal.comment.comment.block.jade</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*(//)</string>
					<key>name</key>
					<string>string.comment.buffered.block.jade</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(script)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>script.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[(])</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>stuff.tag.script.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(style)</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.script.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>style.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=[(])</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>stuff.tag.script.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#tag_attributes</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>source.css</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*):(markdown)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.markdown.filter.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.markdown.filter.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.html.markdown</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*):(sass)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.sass.filter.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.sass.filter.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.sass</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*):(less)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.less.filter.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.less.filter.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.less</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*):(coffeescript)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.coffeescript.filter.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.coffeescript.filter.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.coffee</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*):(\w+)$</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language.name.generic.filter.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.generic.filter.jade</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)((-\s)|(?i:[a-z0-9_]*\s+=))</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>javascript.embedded.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(mixin)\s+([\w-]+)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.jade</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.mixin.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(\()</string>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.args.mixin.jade</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\))</string>
					<key>name</key>
					<string>meta.args.mixin.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*(for|if|else if|else|each|until|while|unless)(\s+|$)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.control.flow.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>.</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>js.embedded.control.flow.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s+)(?=[a-z.#].*?\.$)</string>
			<key>end</key>
			<string>^(?!(\1\s)|\s*$)</string>
			<key>name</key>
			<string>text.block.dot.tag.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#complete_tag</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?=.)</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>text.block.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html_entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_value</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([a-z#.])(?=.*?\.$)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.tag.name</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\s|$)</string>
			<key>name</key>
			<string>text.block.dot.tag.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#complete_tag</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(?=.)</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>text.block.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html_entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_value</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^\s*</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>tag.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\|</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>text.block.pipe.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#html_entity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolated_value</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#printed_expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#complete_tag</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>invalid.illegal.tag.jade</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>complete_tag</key>
		<dict>
			<key>begin</key>
			<string>(?=[a-z.#])</string>
			<key>end</key>
			<string>(?!:\s+)$</string>
			<key>name</key>
			<string>complete_tag.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag_name</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_id</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_classes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_attributes</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(\.(?!$))|(:\s*([^\sa-z.#]|$))</string>
					<key>name</key>
					<string>invalid.illegal.end.tag.jade</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>:\s*</string>
					<key>end</key>
					<string>(?!:)$</string>
					<key>name</key>
					<string>subtag.complete_tag.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#complete_tag</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#printed_expression</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#tag_text</string>
				</dict>
			</array>
		</dict>
		<key>html_entity</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&amp;(?!((#\d+)|([a-z]\w+));)</string>
					<key>name</key>
					<string>invalid.illegal.html_entity.text.jade</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;((#\d+)|([a-z]\w+));</string>
					<key>name</key>
					<string>constant.html_entity.text.jade</string>
				</dict>
			</array>
		</dict>
		<key>interpolated_value</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)[#!]\{</string>
			<key>end</key>
			<string>\}</string>
			<key>name</key>
			<string>string.interpolated.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>printed_expression</key>
		<dict>
			<key>begin</key>
			<string>(!?=)\s*</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.js</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>begin</key>
			<string>(['"])</string>
			<key>end</key>
			<string>(?&lt;!\\)\1</string>
			<key>name</key>
			<string>string.quoted.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolated_value</string>
				</dict>
			</array>
		</dict>
		<key>tag_attributes</key>
		<dict>
			<key>begin</key>
			<string>(\()</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.name.attribute.tag.jade</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>name</key>
			<string>attibutes.tag.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>([a-z]\w+)(=)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.tag.jade</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.separator.key-value.jade</string>
						</dict>
					</dict>
					<key>end</key>
					<string>,|(?=\))</string>
					<key>name</key>
					<string>attributes.tag.jade</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>tag_classes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.name.classes.tag.jade</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\.([\w-]+)</string>
			<key>name</key>
			<string>classes.tag.jade</string>
		</dict>
		<key>tag_id</key>
		<dict>
			<key>match</key>
			<string>#([a-z][\w-]*)</string>
			<key>name</key>
			<string>constant.id.tag.jade</string>
		</dict>
		<key>tag_name</key>
		<dict>
			<key>match</key>
			<string>[a-z][a-z0-9_-]*</string>
			<key>name</key>
			<string>entity.name.tag.jade</string>
		</dict>
		<key>tag_text</key>
		<dict>
			<key>begin</key>
			<string>(?=.)</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>text.jade</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#html_entity</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_value</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.jade</string>
	<key>uuid</key>
	<string>eee6ba25-6ac2-4f7e-9c70-cddf2bd3448b</string>
</dict>
</plist>
